# .goreleaser.yml
# Build customization
builds:
    -   main: interlook.go
binary: interlook
goos:
    - windows
    - darwin
    - linux
goarch:
    - amd64
# Archive customization
archive:
    format: tar.gz
