# .goreleaser.yml
builds:
    -   main: interlook.go
        binary: interlook
        ldflags:
            - -s -w -X main.build={{.Version}}
        env:
            - CGO_ENABLED=0
        goos:
            - linux
        goarch:
            - amd64
archives:
    -   replacements:
            darwin: Darwin
            linux: Linux
            windows: Windows
            amd64: x86_64
checksum:
    name_template: 'checksums.txt'
snapshot:
    name_template: "{{ .Tag }}-next"
changelog:
    sort: asc
    filters:
        exclude:
            - '^docs:'
            - '^test:'
