# .travis.yml
language: go
go:
    - 1.13.4
install: true
sudo: required
before_install:
    - go get github.com/mattn/goveralls
    - go get golang.org/x/tools/cmd/cover
script:
    - go test ./... -v -covermode=count -coverprofile=coverage.out
    - goveralls -v -coverprofile=coverage.out -service=travis-ci
