# .travis.yml
language: go
go:
    - 1.13.4
install: true
sudo: required
before_install:
    - GO111MODULE=off go get github.com/mattn/goveralls
    - GO111MODULE=off go get golang.org/x/tools/cmd/cover
script:
    - go test ./... -v -covermode=count -coverprofile=coverage.out
    - goveralls -v -coverprofile=coverage.out -service=travis-ci
deploy:
    -   provider: script
        skip_cleanup: true
        script: curl -sL https://git.io/goreleaser | bash
        on:
            tags: true
            condition: $TRAVIS_OS_NAME = linux
