---
core:
  logLevel: DEBUG
  listenPort: 8080
  logFile : /toto.log
  workflow: provider.docker,ipam.file,dns.consul
  checkFlowInterval: 2s
  flowEntriesFile: ./share/flowentries.db
provider:
  docker:
    name: myDocker
    endpoint: tcp://docker.net:443
    labelSelector:
      - interlook.host
    tlsCa: path/to/ca
    tlsCert: path/to/cert
    tlsKey: path/to/key
    Watch: true
    WatchInterval: 10s
    updateInterval: 15s
ipam:
  file:
    ip_start:
    ip_end:
    network_cidr: 192.168.1.0/24
    db_file: ./share/conf/allocated.db
dns:
  consul:
    url: http://127.0.0.1:8500
    domain: docker.com
    token:
loadbalancer:
  f5:
    endpoint: http://myf5.local:10000
    token: nvajnfva-avsv  
