---
core:
  logLevel: DEBUG
  listenPort: 8080
  logFile : stdout
  workflow: provider.swarm,ipam.ipalloc,lb.f5ltm
  workflowControlInterval: 3s
  cleanUndeployedServiceAfer: 10m
  reconcileServiceWihtProviderInterval: 5m
  flowEntriesFile: ./share/flowentries.db

provider:
  swarm:
    endpoint: tcp://ucp.csnet.me:443
    labelSelector:
      - interlook.hosts
    tlsCa: /home/michael/dkr/bundle/admin/ca.pem
    tlsCert: /home/michael/dkr/bundle/admin/cert.pem
    tlsKey: /home/michael/dkr/bundle/admin/key.pem
    pollInterval: 15s

ipam:
  ipalloc:
    network_cidr: 10.32.30.0/24
    db_file: ./share/ipalloc.db

dns:
  consul:
    url: http://127.0.0.1:8500
    domain:
    token:

lb:
  kemplm:
    endpoint: https://192.168.99.2
    username: api
    password: apiPassw0rd
    httpPort: 80
    httpsPort: 443

  f5ltm:
    httpEndpoint: https://10.32.20.100
    username: api
    password: default
    authProvider: tmos
    authToken:
    httpPort: 80
    httpsPort: 443
    monitorName: tcp
    tcpProfile:
    partition: interlook
    loadBalancingMode: least-connections-member

