---
core:
    logLevel: INFO
  listenPort: 8080
  logFile : stdout
    workflowSteps: provider.swarm,ipam.ipalloc,dns.consul,lb.f5ltm
  workflowEntriesFile: ./share/flowentries.db
    workflowActivityLauncherInterval: 3s
    workflowHousekeeperInterval: 60s
  serviceWIPTimeout: 90s
  cleanUndeployedServiceAfter: 10m
  serviceMaxLastUpdated: 90s

provider:
  swarm:
    endpoint: tcp://ucp.csnet.me:443
    labelSelector:
        - l7aas
    tlsCa: /home/michael/dkr/bundle/admin/ca.pem
    tlsCert: /home/michael/dkr/bundle/admin/cert.pem
    tlsKey: /home/michael/dkr/bundle/admin/key.pem
    pollInterval: 5s

ipam:
  ipalloc:
    network_cidr: 10.32.30.0/24
    db_file: ./share/ipalloc.db

dns:
  consul:
    url: http://127.0.0.1:8500
    domain:
    token:

lb:
  kemplm:
    endpoint: https://192.168.99.2
    username: api
    password: apiPassw0rd
    httpPort: 80
    httpsPort: 443

  f5ltm:
    httpEndpoint: https://10.32.20.100
    username: api
    password: default
    authProvider: tmos
    authToken:
    httpPort: 80
    httpsPort: 443
    monitorName: tcp
    tcpProfile:
    partition: interlook
    loadBalancingMode: least-connections-member

