---
core:
  logLevel: DEBUG
  listenPort: 8080
  logFile : stdout
  workflow: provider.docker,ipam.ipalloc,lb.f5ltm
  workflowControlInterval: 5s
  cleanUndeployedServiceAfer: 10m
  reconcileServiceWihtProviderInterval: 5m
  flowEntriesFile: ./share/flowentries.db

provider:
  docker:
    name: myDocker
    endpoint: tcp://docker.net:443
    labelSelector:
      - interlook.host
    tlsCa: path/to/ca
    tlsCert: path/to/cert
    tlsKey: path/to/key
    Watch: true
    WatchInterval: 10s
    updateInterval: 15s

ipam:
  ipalloc:
    network_cidr: 10.32.30.0/24
    db_file: ./share/ipalloc.db

dns:
  consul:
    url: http://127.0.0.1:8500
    domain:
    token:

lb:
  kemplm:
    endpoint: https://192.168.99.2
    username: api
    password: apiPassw0rd
    httpPort: 80
    httpsPort: 443

  f5ltm:
    httpEndpoint: https://10.32.20.100
    username: api
    password: default
    authProvider: tmos
    authToken:
    httpPort: 80
    httpsPort: 443
    monitorName: tcp
    tcpProfile:
    partition:
    loadBalancingMode: least-connections-member

