---
core:
  logLevel: DEBUG
  listenPort: 8080
  logFile : stdout
  workflow: provider.docker,ipam.ipalloc,dns.consul,lb.kemplm
  checkFlowInterval: 5s
  flowEntriesFile: ./share/flowentries.db
provider:
  docker:
    name: myDocker
    endpoint: tcp://docker.net:443
    labelSelector:
      - interlook.host
    tlsCa: path/to/ca
    tlsCert: path/to/cert
    tlsKey: path/to/key
    Watch: true
    WatchInterval: 10s
    updateInterval: 15s
ipam:
  ipalloc:
    network_cidr: 192.168.99.0/24
    db_file: ./share/conf/allocated.db
dns:
  consul:
    url: http://127.0.0.1:8500
    domain:
    token:
lb:
  kemplm:
    endpoint: https://192.168.99.2
    username: api
    password: apiPassw0rd
